name: pi-bluetooth
version: '1.1'
summary: Setup Bluetooth on Raspberry Pi running Ubuntu Core
description: |
  Confined snap meant to enable bluetooth on RPi devices on Ubuntu Core systems
grade: devel
confinement: strict
base: core18
architectures:
  - build-on: armhf
  - build-on: arm64

apps:
  btuart:
    command: btuart
    daemon: forking
    plugs:
      - serial-port
      - hardware-observe
      - bluetooth-control
  bthelper:
    command: bthelper
    daemon: oneshot
    after:
      - btuart
    plugs:
      - serial-port
      - hardware-observe
      - bluetooth-control
      - network-observe

parts:
  file-dump:
    plugin: dump
    source: dump
  bluez:
    plugin: nil
    stage-snaps: 
      - bluez
    prime:
      - usr/bin/hciconfig
      - usr/bin/hcidump
      - usr/bin/hciattach
      - usr/bin/hcitool
